### ISSUE TITLE
First Usable Version

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/AutoTx#7]
- [ ] User-Friendly CLI
  - [x] [Console Logging](https://github.com/polywrap/sage-agent/issues/8)
  - [ ] (stretch) Per Transaction Confidence & Risk Scores
- [ ] Developer-Friendly Repo
  - [x] [Easily Add New Agents & Tools](https://github.com/polywrap/sage-agent/issues/9)
  - [x] [Easily Add Benchmarks](https://github.com/polywrap/sage-agent/issues/10)
  - [x] [README: description, how-to run/customize/test, roadmap (done, not done)](https://github.com/polywrap/sage-agent/issues/11)
- [ ] Safe Integration
  - [ ] (stretch) [Support Existing Safes](https://github.com/polywrap/sage-agent/issues/12)
  - [x] [Create A New Safe](https://github.com/polywrap/sage-agent/issues/13)
  - [x] [Batched Transactions](https://github.com/polywrap/sage-agent/issues/14)
- [ ] Use-Case Benchmarks
  - [x] ERC20: [Send](https://github.com/polywrap/sage-agent/issues/15), [Swap](https://github.com/polywrap/sage-agent/issues/16) (single dex)
  - [ ] (stretch) NFT: Send, Mint, Buy, Sell
  - [ ] (stretch) ERC20: Bridge
